### ISSUE TITLE
Cobra.test module is missing

### ISSUE THREAD

**Issue by AhmedElsherbini** [manuelgloeckler/ncmw#7]
Hi Manuel,

Firstly, thank you for this good work which is very interesting for my own project.

I have installed your package as instructed. However, I do witness some conflicts with Cobra. So in Cobra (version 0.25.0) where other modules do exist like (io, model, reaction,.....).

```python
Traceback (most recent call last):
  File "/home/ahmed/anaconda3/bin/ncmw", line 33, in <module>
    sys.exit(load_entry_point('ncmw', 'console_scripts', 'ncmw')())
  File "/home/ahmed/anaconda3/bin/ncmw", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/ahmed/anaconda3/lib/python3.9/importlib/metadata.py", line 86, in load
    module = import_module(match.group('module'))
  File "/home/ahmed/anaconda3/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/ahmed/ncmw/ncmw/scripts/ncmw_scripts.py", line 1, in <module>
    from .setup_scripts import run_setup as run1
  File "/home/ahmed/ncmw/ncmw/scripts/setup_scripts.py", line 30, in <module>
    from ncmw.setup_models import *
  File "/home/ahmed/ncmw/ncmw/setup_models/__init__.py", line 1, in <module>
    from .setup import (
  File "/home/ahmed/ncmw/ncmw/setup_models/setup.py", line 2, in <module>
    import cobra.test
ModuleNotFoundError: No module named 'cobra.test'
```
Any clue for help?

**Comment by manuelgloeckler** [comment]
Hey Ahmed,

thank you for reporting it! Indeed it is due to the new cobra version, which removes the "test" module from the main package. 

I removed the code that relied on it, so if you reinstall the package from scratch it should work now. Alternatively, you can just downgrade your cobra i.e. with `pip install cobra==0.23.0`.

Kind regards
Manuel

**Comment by draeger** [comment]
Should this issue be closed?

**Comment by AhmedElsherbini** [comment]
Thanks, Manuel and Andreas for the fast response.

Now it is working initially, this issue should be closed.
